# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_view_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 513)
        self.labelFormDate = QtWidgets.QLabel(Form)
        self.labelFormDate.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.labelFormDate.setObjectName("labelFormDate")
        self.labelToDate = QtWidgets.QLabel(Form)
        self.labelToDate.setGeometry(QtCore.QRect(210, 30, 51, 16))
        self.labelToDate.setObjectName("labelToDate")
        self.FormDate = QtWidgets.QDateEdit(Form)
        self.FormDate.setGeometry(QtCore.QRect(90, 30, 110, 22))
        self.FormDate.setObjectName("FormDate")
        self.FormDate_2 = QtWidgets.QDateEdit(Form)
        self.FormDate_2.setGeometry(QtCore.QRect(260, 30, 110, 22))
        self.FormDate_2.setObjectName("FormDate_2")
        self.labelAnexo = QtWidgets.QLabel(Form)
        self.labelAnexo.setGeometry(QtCore.QRect(20, 70, 49, 16))
        self.labelAnexo.setObjectName("labelAnexo")
        self.TextAnexo = QtWidgets.QLineEdit(Form)
        self.TextAnexo.setGeometry(QtCore.QRect(70, 70, 113, 21))
        self.TextAnexo.setObjectName("TextAnexo")
        self.labelNumero = QtWidgets.QLabel(Form)
        self.labelNumero.setGeometry(QtCore.QRect(20, 110, 49, 16))
        self.labelNumero.setObjectName("labelNumero")
        self.TextNumero = QtWidgets.QLineEdit(Form)
        self.TextNumero.setGeometry(QtCore.QRect(70, 110, 113, 21))
        self.TextNumero.setObjectName("TextNumero")
        self.LabelImport = QtWidgets.QLabel(Form)
        self.LabelImport.setGeometry(QtCore.QRect(20, 160, 49, 16))
        self.LabelImport.setObjectName("LabelImport")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(70, 160, 21, 22))
        self.toolButton.setObjectName("toolButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 200, 421, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Buscar = QtWidgets.QPushButton(Form)
        self.Buscar.setGeometry(QtCore.QRect(320, 160, 75, 24))
        self.Buscar.setObjectName("Buscar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #conectar el boton toolButton a la funcion openFileNameDialog
        self.toolButton.clicked.connect(self.open_file_dialog)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelFormDate.setText(_translate("Form", "FormDate:"))
        self.labelToDate.setText(_translate("Form", "ToDate:"))
        self.labelAnexo.setText(_translate("Form", "Anexo:"))
        self.labelNumero.setText(_translate("Form", "Numero:"))
        self.LabelImport.setText(_translate("Form", "Import"))
        self.toolButton.setText(_translate("Form", "..."))
        self.Buscar.setText(_translate("Form", "buscarButton"))

    def open_file_dialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        file_name, _ = QFileDialog.getOpenFileName(None, "Select File", "", "All Files (*);;Excel Files (*.xlsx;*.xls)", options=options)
        if file_name:
            file_base_name = os.path.basename(file_name)
            self.toolButton.setText(file_base_name)  # Mostrar la ruta del archivo en el cuadro de texto (TextEdit)
             # Cambiar el tamaño del botón toolButton
            self.toolButton.setFixedWidth(100)  # Aumenta el ancho del botón
           

#if __name__ == "__main__":
#    import sys
#    app = QtWidgets.QApplication(sys.argv)
#    Form = QtWidgets.QWidget()
#    ui = Ui_Form()
#    ui.setupUi(Form)
#   Form.show()
#    sys.exit(app.exec_())
